# frozen_string_literal: true

require "date"
module Plansheet
  # The Sheet class constructs a Markdown/LaTeX file for use with pdflatex
  class LaTeXSheet
    include LaTeXMixins
    def initialize(output_file, project_arr)
      projects_str = String.new
      projects_str << sheet_header
      projects_str << document do
        "\\thispagestyle{empty}\n\n\\section{Date: #{Date.today}}\n".concat(
          project_arr.map do |p|
            project_minipage(p)
          end.join
        )
      end
      puts "Writing to #{output_file}"
      File.write(output_file, projects_str)
    end

    def sheet_header
      # LaTeX used to be generated by pandoc
      <<~FRONTMATTER
        \\PassOptionsToPackage{unicode}{hyperref}
        \\PassOptionsToPackage{hyphens}{url}
        \\documentclass[]{article}
        \\author{}
        \\date{#{Date.today}}
        \\usepackage{amsmath,amssymb}
        \\usepackage{lmodern}
        \\usepackage{iftex}
          \\usepackage[T1]{fontenc}
          \\usepackage[utf8]{inputenc}
          \\usepackage{textcomp}
        \\IfFileExists{upquote.sty}{\\usepackage{upquote}}{}
        \\IfFileExists{microtype.sty}{
          \\usepackage[]{microtype}
          \\UseMicrotypeSet[protrusion]{basicmath}
        }{}
        \\makeatletter
        \\@ifundefined{KOMAClassName}{
          \\IfFileExists{parskip.sty}{
            \\usepackage{parskip}
          }{
            \\setlength{\\parindent}{0pt}
            \\setlength{\\parskip}{6pt plus 2pt minus 1pt}}
        }{
          \\KOMAoptions{parskip=half}}
        \\makeatother
        \\usepackage{xcolor}
        \\IfFileExists{xurl.sty}{\\usepackage{xurl}}{}
        \\IfFileExists{bookmark.sty}{\\usepackage{bookmark}}{\\usepackage{hyperref}}
        \\hypersetup{
          hidelinks,
          pdfcreator={LaTeX via plansheet}}
        \\urlstyle{same}
        \\usepackage[margin=1.5cm]{geometry}
        \\setlength{\\emergencystretch}{3em}
        \\providecommand{\\tightlist}{
          \\setlength{\\itemsep}{0pt}\\setlength{\\parskip}{0pt}}
        \\setcounter{secnumdepth}{-\\maxdimen}
      FRONTMATTER
    end

    def project_minipage(proj)
      minipage("6cm") do
        project_header(proj)&.concat(
          proj&.tasks&.map do |t|
            "#{checkbox_item sanitize_string(t)}#{HARD_NL}"
          end&.join("") || "" # empty string to catch nil
        )
      end
    end

    def project_header(proj)
      str = String.new
      str << "#{sanitize_string(proj.namespace)}: #{sanitize_string(proj.name)}#{HARD_NL}"
      str << proj.status.to_s
      str << " - #{sanitize_string(proj.location)}" if proj.location
      str << " due: #{proj.due}" if proj.due
      str << " time: #{proj.time_estimate}" if proj.time_estimate
      str << HARD_NL
      str
    end
  end
end
