#!/usr/bin/env ruby
# frozen_string_literal: true

# An ugly script to sort projects by status (and eventually priority)

require "yaml"
require "plansheet"

def project_priority(project)
  if project["status"]
    project["status"]
  elsif project["tasks"]
    "planning"
  else
    "idea"
  end
end

filename = ARGV.first
contents = YAML.load_file(filename)
sorted_hash = contents.sort_by do |project|
  Plansheet::PROJECT_STATUS_PRIORITY[project_priority project]
end

File.write(filename, YAML.dump(sorted_hash))
