#!/usr/bin/env ruby
# frozen_string_literal: true

require "plansheet"

config = Plansheet.load_config

project_arr = Plansheet.load_projects_dir config["projects_dir"]

Dir.mkdir config["output_dir"] unless Dir.exist? config["output_dir"]

Plansheet::Sheet.new("#{config["output_dir"]}/projects.md", project_arr)
